[versions]
checkstyle = "10.5.0"
platform = "2023.01.21"

[libraries]
gradleplugins-cpd = {group = "de.aaschmid", name = "gradle-cpd-plugin", version = "3.3" }
gradleplugins-errorprone = {group = "net.ltgt.gradle", name = "gradle-errorprone-plugin", version = "3.0.1" }
gradleplugins-nullaway = {group = "net.ltgt.gradle", name = "gradle-nullaway-plugin", version = "1.5.0" }
gradleplugins-pitest = {group = "info.solidsoft.gradle.pitest", name = "gradle-pitest-plugin", version = "1.9.11" }
gradleplugins-spotbugs = {group = "com.github.spotbugs.snom", name = "spotbugs-gradle-plugin", version = "5.0.13" }
gradleplugins-testLogger = {group = "com.adarshr", name = "gradle-test-logger-plugin", version = "3.2.0" }

gradleplugins-library-nullaway = {group = "com.uber.nullaway", name = "nullaway", version = "0.10.5" }
gradleplugins-library-errorprone = {group = "com.google.errorprone", name = "error_prone_core", version = "2.16" }
gradleplugins-library-findbugsJsr305 = {group = "com.google.code.findbugs", name = "jsr305", version = "3.0.2" }

testing-assertJ = {group = "org.assertj", name = "assertj-bom", version = "3.24.1" }
testing-slf4jTest = {group = "com.github.valfirst", name = "slf4j-test", version = "2.7.0" }
testing-archunit = {group = "com.tngtech.archunit", name = "archunit", version = "1.0.1" }
testing-equalsverifier = {group = "nl.jqno.equalsverifier", name = "equalsverifier", version = "3.12.2" }
testing-awaitility = { group = "org.awaitility", name = "awaitility", version = "4.2.0" }

caffeine = {group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.2" }
guava = {group = "com.google.guava", name = "guava", version = "31.1-jre" }
metricsSpring = {group = "com.ryantenney.metrics", name = "metrics-spring", version = "3.1.3" }
commonsCodec = {group = "commons-codec", name = "commons-codec", version = "1.15" }
resilience4jSpringBoot2 = {group = "io.github.resilience4j", name = "resilience4j-spring-boot2", version = "2.0.2" }
resilience4jSpringBoot3 = {group = "io.github.resilience4j", name = "resilience4j-spring-boot3", version = "2.0.2" }
javaxAnnotationApi = {group = "javax.annotation", name = "javax.annotation-api", version = "1.3.2" }
commonsLang = {group = "org.apache.commons", name = "commons-lang3", version = "3.12.0" }
eclipseCollections = {group = "org.eclipse.collections", name = "eclipse-collections", version = "11.1.0" }
ini4j = {group = "org.ini4j", name = "ini4j", version = "0.5.4" }
bootstrap = {group = "org.webjars", name = "bootstrap", version = "5.2.3" }
webjarsLocator = {group = "org.webjars", name = "webjars-locator", version = "0.46" }
logbackClassic = {group = "ch.qos.logback", name = "logback-classic", version = "1.4.5" }
slf4jApi = {group = "org.slf4j", name = "slf4j-api", version = "2.0.6" }
